# Generated by Django 6.1.1 on 2026-09-15 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prompt',
            options={'ordering': ['-updated_at'], 'verbose_name_plural': 'Prompts'},
        ),
        migrations.AlterUniqueTogether(
            name='prompthistory',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_prompts', to='prompts.category'),
        ),
        migrations.AddConstraint(
            model_name='prompthistory',
            constraint=models.UniqueConstraint(fields=('prompt', 'version_number'), name='unique_prompt_version'),
        ),
    ]
